# The Spot config file, containing the parameters for the simulation environment.

mode: train

task:
  name: Spot-Badminton-Train 
  num_envs: 4096
  headless: true
  resume: true 
  run_folder: 2026-07-05_14-57-21
  checkpoint: model_1200.pt

play:
  folder: 2026-07-03_13-44-53
  checkpoint: model_2800.pt

sim:
  env_path: miniconda3/envs/isaac450/lib/python3.10/site-packages/isaacsim/exts/isaacsim.examples.interactive/isaacsim/examples/interactive/user_examples
  scripts: ["go2_example.py", "go2_example_extension.py"]

convert:
  urdf_in: robotarium/spot/urdf/spot_badminton.urdf
  usd_out: robotarium/spot/usd/spot_badminton/spot_badminton.usd

transfer:
  source_path: /projects/siliconsynapselab/sslab_isaaclab/logs/rsl_rl/spot_badminton_rl
  log_name: 2026-07-03_13-44-53
  dest_path: logs/rsl_rl/spot_badminton_rl

visuals:
  enable: true
  video_length: 400
  video_interval: 10000

slurm:
  job_name: sslab_spot_rl
  nodes: 1
  tasks_per_node: 1
  cpus_per_task: 2
  gres: gpu:a100:1
  mem: 128GB
  partition: gpu
  time: "8:00:00"
  output: "/projects/siliconsynapselab/sslab_isaaclab/hpc_logs/spot/output_%j.txt"
  error:  "/projects/siliconsynapselab/sslab_isaaclab/hpc_logs/spot/error_%j.txt"

container:
  docker_user: arjunviswanathan        # your Docker Hub username
  image_name: sslab-isaaclab           # repo name on Docker Hub
  image_tag: 20260705-125554
  convert:
    urdf_in: /workspace/robotarium/spot/urdf/spot_badminton.urdf
    usd_out: /workspace/robotarium/spot/usd/spot_badminton/spot_badminton.usd

hpc:
  user: viswanathan.ar
  host: login.explorer.northeastern.edu
  project_dir: /projects/siliconsynapselab/sslab_isaaclab
  container_dir: /projects/siliconsynapselab/containers
  run_dir_base: /projects/siliconsynapselab/sslab_isaaclab/logs  # logs/checkpoints bind here
  apptainer_cache: /projects/siliconsynapselab/container_images/cache
  apptainer_tmp: /projects/siliconsynapselab/container_images/tmp
